import { Card } from "./card";

export class Deck{
    static cardDeck : Card[] = [
        {id : 1, color : 'brown', action : 'property', price : 10, description : 'Рента: 1 карта - 1M; 2 карты - 2M', name : 'Kasarmikatu'},
        {id : 2, color : 'brown', action : 'property', price : 10, description : 'Рента: 1 карта - 1M; 2 карты - 2M', name : 'Korkeavuorenkatu'},
        {id : 2, color : 'brown', action : 'property', price : 10, description : 'Рента: 1 карта - 1M; 2 карты - 2M', name : 'Hesperiankatu'},
        {id : 3, color : 'light-blue', action : 'property', price : 10, description : 'Рента: 1 карта - 1M; 2 карты - 2M; 3 карты - 3M', name : 'Esplanadi'},
        {id : 3, color : 'light-blue', action : 'property', price : 10, description : 'Рента: 1 карта - 1M; 2 карты - 2M; 3 карты - 3M', name : 'Kauppatori'},
        {id : 4, color : 'light-blue', action : 'property', price : 10, description : 'Рента: 1 карта - 1M; 2 карты - 2M; 3 карты - 3M', name : 'Rantatie'},
        {id : 5, color : 'light-blue', action : 'property', price : 10, description : 'Рента: 1 карта - 1M; 2 карты - 2M; 3 карты - 3M', name : 'Toinentie'},
        {id : 5, color : 'light-blue', action : 'property', price : 10, description : 'Рента: 1 карта - 1M; 2 карты - 2M; 3 карты - 3M', name : 'Kolmastie'},
        {id : 6, color : 'pink', action : 'property', price : 10, description : 'Рента: 1 карта - 1M; 2 карты - 2M; 3 карты - 4M', name : 'Hameentie'},
        {id : 7, color : 'pink', action : 'property', price : 10, description : 'Рента: 1 карта - 1M; 2 карты - 2M; 3 карты - 4M', name : 'Kaisaniemenkatu'},
        {id : 8, color : 'pink', action : 'property', price : 10, description : 'Рента: 1 карта - 1M; 2 карты - 2M; 3 карты - 4M', name : 'Siltasaari'},
        {id : 7, color : 'pink', action : 'property', price : 10, description : 'Рента: 1 карта - 1M; 2 карты - 2M; 3 карты - 4M', name : 'Kalevankatu'},
        {id : 8, color : 'pink', action : 'property', price : 10, description : 'Рента: 1 карта - 1M; 2 карты - 2M; 3 карты - 4M', name : 'Eerikinkatu'},
        {id : 9, color : 'orange', action : 'property', price : 10, description : 'Рента: 1 карта - 1M; 2 карты - 3M; 3 карты - 5M', name : 'Liisankatu'},
        {id : 9, color : 'orange', action : 'property', price : 10, description : 'Рента: 1 карта - 1M; 2 карты - 3M; 3 карты - 5M', name : 'Snellmaninkatu'},
        {id : 9, color : 'orange', action : 'property', price : 10, description : 'Рента: 1 карта - 1M; 2 карты - 3M; 3 карты - 5M', name : 'Unioninkatu'},
        {id : 9, color : 'orange', action : 'property', price : 10, description : 'Рента: 1 карта - 1M; 2 карты - 3M; 3 карты - 5M', name : 'Jallaranta'},
        {id : 9, color : 'orange', action : 'property', price : 10, description : 'Рента: 1 карта - 1M; 2 карты - 3M; 3 карты - 5M', name : 'Karibianranta'},
        {id : 10, color : 'red', action : 'property', price : 10, description : 'Рента: 1 карта - 2M; 2 карты - 3M; 3 карты - 6M', name : 'Lonnrotinkatu'},
        {id : 11, color : 'red', action : 'property', price : 10, description : 'Рента: 1 карта - 2M; 2 карты - 3M; 3 карты - 6M', name : 'Simonkatu'},
        {id : 12, color : 'red', action : 'property', price : 10, description : 'Рента: 1 карта - 2M; 2 карты - 3M; 3 карты - 6M', name : 'Annankatu'},
        {id : 11, color : 'red', action : 'property', price : 10, description : 'Рента: 1 карта - 2M; 2 карты - 3M; 3 карты - 6M', name : 'Samoankuja'},
        {id : 12, color : 'red', action : 'property', price : 10, description : 'Рента: 1 карта - 2M; 2 карты - 3M; 3 карты - 6M', name : 'Kanariankatu'},
        {id : 12, color : 'yellow', action : 'property', price : 10, description : 'Рента: 1 карта - 2M; 2 карты - 4M; 3 карты - 6M', name : 'Aleksanterinkatu'},
        {id : 12, color : 'yellow', action : 'property', price : 10, description : 'Рента: 1 карта - 2M; 2 карты - 4M; 3 карты - 6M', name : 'Keskuskatu'},
        {id : 12, color : 'yellow', action : 'property', price : 10, description : 'Рента: 1 карта - 2M; 2 карты - 4M; 3 карты - 6M', name : 'Mikonkatu'},
        {id : 12, color : 'yellow', action : 'property', price : 10, description : 'Рента: 1 карта - 2M; 2 карты - 4M; 3 карты - 6M', name : 'Laippatie'},
        {id : 12, color : 'yellow', action : 'property', price : 10, description : 'Рента: 1 карта - 2M; 2 карты - 4M; 3 карты - 6M', name : 'Pulttitie'},
        {id : 12, color : 'green', action : 'property', price : 10, description : 'Рента: 1 карта - 2M; 2 карты - 4M; 3 карты - 7M', name : 'Eira'},
        {id : 12, color : 'green', action : 'property', price : 10, description : 'Рента: 1 карта - 2M; 2 карты - 4M; 3 карты - 7M', name : 'Tehtaankatu'},
        {id : 12, color : 'green', action : 'property', price : 10, description : 'Рента: 1 карта - 2M; 2 карты - 4M; 3 карты - 7M', name : 'Bulevardi'},
        {id : 12, color : 'green', action : 'property', price : 10, description : 'Рента: 1 карта - 2M; 2 карты - 4M; 3 карты - 7M', name : 'Sopultie'},
        {id : 12, color : 'green', action : 'property', price : 10, description : 'Рента: 1 карта - 2M; 2 карты - 4M; 3 карты - 7M', name : 'Siilitie'},
        {id : 12, color : 'blue', action : 'property', price : 10, description : 'Рента: 1 карта - 3M; 2 карты - 8M', name : 'Mannerheimintie'},
        {id : 12, color : 'blue', action : 'property', price : 10, description : 'Рента: 1 карта - 3M; 2 карты - 8M', name : 'Erottajala'},
        {id : 12, color : 'blue', action : 'property', price : 10, description : 'Рента: 1 карта - 3M; 2 карты - 8M', name : 'Ahmatie'},
        {id : 12, color : 'station', action : 'property', price : 10, description : 'Рента: 1 карта - 1M; 2 карты - 2M; 3 карты - 3M; 4 карты - 4M', name : 'Sornaistenasema'},
        {id : 12, color : 'station', action : 'property', price : 10, description : 'Рента: 1 карта - 1M; 2 карты - 2M; 3 карты - 3M; 4 карты - 4M', name : 'Pasilanasema'},
        {id : 12, color : 'station', action : 'property', price : 10, description : 'Рента: 1 карта - 1M; 2 карты - 2M; 3 карты - 3M; 4 карты - 4M', name : 'Rautatieasema'},
        {id : 12, color : 'station', action : 'property', price : 10, description : 'Рента: 1 карта - 1M; 2 карты - 2M; 3 карты - 3M; 4 карты - 4M', name : 'Tavaraaasema'},
        {id : 12, color : 'station', action : 'property', price : 10, description : 'Рента: 1 карта - 1M; 2 карты - 2M; 3 карты - 3M; 4 карты - 4M', name : 'Kapylanasema'},
        {id : 12, color : 'station', action : 'property', price : 10, description : 'Рента: 1 карта - 1M; 2 карты - 2M; 3 карты - 3M; 4 карты - 4M', name : 'Makkylanasema'},
        {id : 12, color : 'station', action : 'property', price : 10, description : 'Рента: 1 карта - 1M; 2 карты - 2M; 3 карты - 3M; 4 карты - 4M', name : 'Illmalaasema'},
        {id : 12, color : 'community', action : 'property', price : 10, description : 'Рента: 1 карта - 1M; 2 карты - 2M;', name : 'Vesilaitos'},
        {id : 12, color : 'community', action : 'property', price : 10, description : 'Рента: 1 карта - 1M; 2 карты - 2M;', name : 'Sahkolaitos'},
        {id : 12, color : 'community', action : 'property', price : 10, description : 'Рента: 1 карта - 1M; 2 карты - 2M;', name : 'Metsatalo'},
        {id : 13, color : 'any', action : 'rent', price : 10, description : 'Рента любого цвета', name : 'Рента'},
        {id : 13, color : 'any', action : 'rent', price : 10, description : 'Рента любого цвета', name : 'Рента'},
        {id : 13, color : 'any', action : 'rent', price : 10, description : 'Рента любого цвета', name : 'Рента'},
        {id : 13, color : 'brown', action : 'rent', price : 10, description : 'Рента коричневого цвета', name : 'Рента'},
        {id : 13, color : 'brown', action : 'rent', price : 10, description : 'Рента коричневого цвета', name : 'Рента'},
        {id : 13, color : 'light-blue', action : 'rent', price : 10, description : 'Рента голубого цвета', name : 'Рента'},
        {id : 13, color : 'light-blue', action : 'rent', price : 10, description : 'Рента голубого цвета', name : 'Рента'},
        {id : 13, color : 'red', action : 'rent', price : 10, description : 'Рента красного цвета', name : 'Рента'},
        {id : 13, color : 'red', action : 'rent', price : 10, description : 'Рента красного цвета', name : 'Рента'},
        {id : 13, color : 'yellow', action : 'rent', price : 10, description : 'Рента жёлтого цвета', name : 'Рента'},
        {id : 13, color : 'yellow', action : 'rent', price : 10, description : 'Рента жёлтого цвета', name : 'Рента'},
        {id : 13, color : 'blue', action : 'rent', price : 10, description : 'Рента синего цвета', name : 'Рента'},
        {id : 13, color : 'blue', action : 'rent', price : 10, description : 'Рента синего цвета', name : 'Рента'},
        {id : 13, color : 'green', action : 'rent', price : 10, description : 'Рента зелёного цвета', name : 'Рента'},
        {id : 13, color : 'green', action : 'rent', price : 10, description : 'Рента зелёного цвета', name : 'Рента'},
        {id : 13, color : 'station', action : 'rent', price : 10, description : 'Рента чёрного цвета', name : 'Рента'},
        {id : 13, color : 'station', action : 'rent', price : 10, description : 'Рента чёрного цвета', name : 'Рента'},
        {id : 13, color : 'community', action : 'rent', price : 10, description : 'Рента песочного цвета', name : 'Рента'},
        {id : 13, color : 'community', action : 'rent', price : 10, description : 'Рента песочного цвета', name : 'Рента'},
        {id : 16, color : 'action', action : 'money', price : 10, description : 'Валюта', name : '10М'},
        {id : 16, color : 'action', action : 'money', price : 5, description : 'Валюта', name : '5М'},
        {id : 16, color : 'action', action : 'money', price : 5, description : 'Валюта', name : '5М'},
        {id : 16, color : 'action', action : 'money', price : 4, description : 'Валюта', name : '4М'},
        {id : 16, color : 'action', action : 'money', price : 4, description : 'Валюта', name : '4М'},
        {id : 16, color : 'action', action : 'money', price : 4, description : 'Валюта', name : '4М'},
        {id : 16, color : 'action', action : 'money', price : 3, description : 'Валюта', name : '3М'},
        {id : 16, color : 'action', action : 'money', price : 3, description : 'Валюта', name : '3М'},
        {id : 16, color : 'action', action : 'money', price : 3, description : 'Валюта', name : '3М'},
        {id : 16, color : 'action', action : 'money', price : 2, description : 'Валюта', name : '2М'},
        {id : 16, color : 'action', action : 'money', price : 2, description : 'Валюта', name : '2М'},
        {id : 16, color : 'action', action : 'money', price : 2, description : 'Валюта', name : '2М'},
        {id : 16, color : 'action', action : 'money', price : 2, description : 'Валюта', name : '2М'},
        {id : 16, color : 'action', action : 'money', price : 2, description : 'Валюта', name : '2М'},
        {id : 16, color : 'action', action : 'money', price : 1, description : 'Валюта', name : '1М'},
        {id : 16, color : 'action', action : 'money', price : 1, description : 'Валюта', name : '1М'},
        {id : 16, color : 'action', action : 'money', price : 1, description : 'Валюта', name : '1М'},
        {id : 16, color : 'action', action : 'money', price : 1, description : 'Валюта', name : '1М'},
        {id : 16, color : 'action', action : 'money', price : 1, description : 'Валюта', name : '1М'},
        {id : 16, color : 'action', action : 'money', price : 1, description : 'Валюта', name : '1М'},
        {id : 17, color : 'action', action : 'unfair', price : 10, description : 'Забери одну карточку собственности из неполного комплекта оппонента', name : 'Нечестная сделка'},
        {id : 17, color : 'action', action : 'unfair', price : 10, description : 'Забери одну карточку собственности из неполного комплекта оппонента', name : 'Нечестная сделка'},
        {id : 17, color : 'action', action : 'unfair', price : 10, description : 'Забери одну карточку собственности из неполного комплекта оппонента', name : 'Нечестная сделка'},
        {id : 17, color : 'action', action : 'unfair', price : 10, description : 'Забери одну карточку собственности из неполного комплекта оппонента', name : 'Нечестная сделка'},
        {id : 19, color : 'action', action : 'steal', price : 10, description : 'Забери весь комлпект собственности оппонента', name : 'Сорви сделку'},
        {id : 19, color : 'action', action : 'steal', price : 10, description : 'Забери весь комлпект собственности оппонента', name : 'Сорви сделку'},
        {id : 19, color : 'action', action : 'justno', price : 10, description : 'Автоматически отменяет действие, направленное против тебя', name : 'Скажи Нет'},
        {id : 19, color : 'action', action : 'justno', price : 10, description : 'Автоматически отменяет действие, направленное против тебя', name : 'Скажи Нет'},
        {id : 19, color : 'action', action : 'justno', price : 10, description : 'Автоматически отменяет действие, направленное против тебя', name : 'Скажи Нет'},
        {id : 14, color : 'action', action : 'tax', price : 10, description : 'Возьми 5M у оппонента', name : 'Сборщик долгов'},
        {id : 14, color : 'action', action : 'tax', price : 10, description : 'Возьми 5M у оппонента', name : 'Сборщик долгов'},
        {id : 14, color : 'action', action : 'tax', price : 10, description : 'Возьми 5M у оппонента', name : 'Сборщик долгов'},
        {id : 15, color : 'action', action : 'birthday', price : 10, description : 'Все оппоненты дают тебе 2M', name : 'День рождения!'},
        {id : 15, color : 'action', action : 'birthday', price : 10, description : 'Все оппоненты дают тебе 2M', name : 'День рождения!'},
        {id : 15, color : 'action', action : 'birthday', price : 10, description : 'Все оппоненты дают тебе 2M', name : 'День рождения!'},
        {id : 14, color : 'action', action : 'start', price : 10, description : 'Тяни ещё 2 карты из колоды', name : 'Пройди через старт'},
        {id : 14, color : 'action', action : 'start', price : 10, description : 'Тяни ещё 2 карты из колоды', name : 'Пройди через старт'},
        {id : 14, color : 'action', action : 'start', price : 10, description : 'Тяни ещё 2 карты из колоды', name : 'Пройди через старт'},
        {id : 14, color : 'action', action : 'start', price : 10, description : 'Тяни ещё 2 карты из колоды', name : 'Пройди через старт'},
        {id : 14, color : 'action', action : 'start', price : 10, description : 'Тяни ещё 2 карты из колоды', name : 'Пройди через старт'},
        {id : 14, color : 'action', action : 'start', price : 10, description : 'Тяни ещё 2 карты из колоды', name : 'Пройди через старт'},
        {id : 14, color : 'action', action : 'start', price : 10, description : 'Тяни ещё 2 карты из колоды', name : 'Пройди через старт'},
        {id : 14, color : 'action', action : 'start', price : 10, description : 'Тяни ещё 2 карты из колоды', name : 'Пройди через старт'},
        {id : 14, color : 'action', action : 'start', price : 10, description : 'Тяни ещё 2 карты из колоды', name : 'Пройди через старт'},
        {id : 14, color : 'action', action : 'start', price : 10, description : 'Тяни ещё 2 карты из колоды', name : 'Пройди через старт'}
    ]
}