import { Card } from "./card";

export class Deck{
    static cardDeck : Card[] = [
        {id : 1, color : 'brown', action : 'property', price : 10, description : '', name : 'brown1'},
        {id : 2, color : 'brown', action : 'property', price : 10, description : '', name : 'brown2'},
        {id : 2, color : 'brown', action : 'property', price : 10, description : '', name : 'brown3'},
        {id : 3, color : 'light-blue', action : 'property', price : 10, description : '', name : 'light-blue1'},
        {id : 3, color : 'light-blue', action : 'property', price : 10, description : '', name : 'light-blue2'},
        {id : 4, color : 'light-blue', action : 'property', price : 10, description : '', name : 'light-blue3'},
        {id : 5, color : 'light-blue', action : 'property', price : 10, description : '', name : 'light-blue4'},
        {id : 5, color : 'light-blue', action : 'property', price : 10, description : '', name : 'light-blue5'},
        {id : 6, color : 'pink', action : 'property', price : 10, description : '', name : 'pink1'},
        {id : 7, color : 'pink', action : 'property', price : 10, description : '', name : 'pink2'},
        {id : 8, color : 'pink', action : 'property', price : 10, description : '', name : 'pink3'},
        {id : 7, color : 'pink', action : 'property', price : 10, description : '', name : 'pink4'},
        {id : 8, color : 'pink', action : 'property', price : 10, description : '', name : 'pink5'},
        {id : 9, color : 'orange', action : 'property', price : 10, description : '', name : 'orange1'},
        {id : 9, color : 'orange', action : 'property', price : 10, description : '', name : 'orange2'},
        {id : 9, color : 'orange', action : 'property', price : 10, description : '', name : 'orange3'},
        {id : 9, color : 'orange', action : 'property', price : 10, description : '', name : 'orange4'},
        {id : 9, color : 'orange', action : 'property', price : 10, description : '', name : 'orange5'},
        {id : 10, color : 'red', action : 'property', price : 10, description : '', name : 'red1'},
        {id : 11, color : 'red', action : 'property', price : 10, description : '', name : 'red2'},
        {id : 12, color : 'red', action : 'property', price : 10, description : '', name : 'red3'},
        {id : 11, color : 'red', action : 'property', price : 10, description : '', name : 'red4'},
        {id : 12, color : 'red', action : 'property', price : 10, description : '', name : 'red5'},
        {id : 12, color : 'yellow', action : 'property', price : 10, description : '', name : 'yellow1'},
        {id : 12, color : 'yellow', action : 'property', price : 10, description : '', name : 'yellow2'},
        {id : 12, color : 'yellow', action : 'property', price : 10, description : '', name : 'yellow3'},
        {id : 12, color : 'yellow', action : 'property', price : 10, description : '', name : 'yellow4'},
        {id : 12, color : 'yellow', action : 'property', price : 10, description : '', name : 'yellow5'},
        {id : 12, color : 'green', action : 'property', price : 10, description : '', name : 'green1'},
        {id : 12, color : 'green', action : 'property', price : 10, description : '', name : 'green2'},
        {id : 12, color : 'green', action : 'property', price : 10, description : '', name : 'green3'},
        {id : 12, color : 'green', action : 'property', price : 10, description : '', name : 'green4'},
        {id : 12, color : 'green', action : 'property', price : 10, description : '', name : 'green5'},
        {id : 12, color : 'blue', action : 'property', price : 10, description : '', name : 'blue1'},
        {id : 12, color : 'blue', action : 'property', price : 10, description : '', name : 'blue2'},
        {id : 12, color : 'blue', action : 'property', price : 10, description : '', name : 'blue3'},
        {id : 12, color : 'station', action : 'property', price : 10, description : '', name : 'station1'},
        {id : 12, color : 'station', action : 'property', price : 10, description : '', name : 'station2'},
        {id : 12, color : 'station', action : 'property', price : 10, description : '', name : 'station3'},
        {id : 12, color : 'station', action : 'property', price : 10, description : '', name : 'station4'},
        {id : 12, color : 'station', action : 'property', price : 10, description : '', name : 'station5'},
        {id : 12, color : 'station', action : 'property', price : 10, description : '', name : 'station6'},
        {id : 12, color : 'station', action : 'property', price : 10, description : '', name : 'station7'},
        {id : 12, color : 'community', action : 'property', price : 10, description : '', name : 'community1'},
        {id : 12, color : 'community', action : 'property', price : 10, description : '', name : 'community2'},
        {id : 12, color : 'community', action : 'property', price : 10, description : '', name : 'community3'},
        {id : 13, color : 'any', action : 'rent', price : 10, description : '', name : 'Рента'},
        {id : 13, color : 'any', action : 'rent', price : 10, description : '', name : 'Рента'},
        {id : 13, color : 'any', action : 'rent', price : 10, description : '', name : 'Рента'},
        {id : 13, color : 'brown', action : 'rent', price : 10, description : '', name : 'Рента'},
        {id : 13, color : 'brown', action : 'rent', price : 10, description : '', name : 'Рента'},
        {id : 13, color : 'light-blue', action : 'rent', price : 10, description : '', name : 'Рента'},
        {id : 13, color : 'light-blue', action : 'rent', price : 10, description : '', name : 'Рента'},
        {id : 13, color : 'red', action : 'rent', price : 10, description : '', name : 'Рента'},
        {id : 13, color : 'red', action : 'rent', price : 10, description : '', name : 'Рента'},
        {id : 13, color : 'yellow', action : 'rent', price : 10, description : '', name : 'Рента'},
        {id : 13, color : 'yellow', action : 'rent', price : 10, description : '', name : 'Рента'},
        {id : 13, color : 'blue', action : 'rent', price : 10, description : '', name : 'Рента'},
        {id : 13, color : 'blue', action : 'rent', price : 10, description : '', name : 'Рента'},
        {id : 13, color : 'green', action : 'rent', price : 10, description : '', name : 'Рента'},
        {id : 13, color : 'green', action : 'rent', price : 10, description : '', name : 'Рента'},
        {id : 13, color : 'station', action : 'rent', price : 10, description : '', name : 'Рента'},
        {id : 13, color : 'station', action : 'rent', price : 10, description : '', name : 'Рента'},
        {id : 13, color : 'community', action : 'rent', price : 10, description : '', name : 'Рента'},
        {id : 13, color : 'community', action : 'rent', price : 10, description : '', name : 'Рента'},
        {id : 16, color : 'action', action : 'money', price : 10, description : '', name : '10М'},
        {id : 16, color : 'action', action : 'money', price : 5, description : '', name : '5М'},
        {id : 16, color : 'action', action : 'money', price : 5, description : '', name : '5М'},
        {id : 16, color : 'action', action : 'money', price : 4, description : '', name : '4М'},
        {id : 16, color : 'action', action : 'money', price : 4, description : '', name : '4М'},
        {id : 16, color : 'action', action : 'money', price : 4, description : '', name : '4М'},
        {id : 16, color : 'action', action : 'money', price : 3, description : '', name : '3М'},
        {id : 16, color : 'action', action : 'money', price : 3, description : '', name : '3М'},
        {id : 16, color : 'action', action : 'money', price : 3, description : '', name : '3М'},
        {id : 16, color : 'action', action : 'money', price : 2, description : '', name : '2М'},
        {id : 16, color : 'action', action : 'money', price : 2, description : '', name : '2М'},
        {id : 16, color : 'action', action : 'money', price : 2, description : '', name : '2М'},
        {id : 16, color : 'action', action : 'money', price : 2, description : '', name : '2М'},
        {id : 16, color : 'action', action : 'money', price : 2, description : '', name : '2М'},
        {id : 16, color : 'action', action : 'money', price : 1, description : '', name : '1М'},
        {id : 16, color : 'action', action : 'money', price : 1, description : '', name : '1М'},
        {id : 16, color : 'action', action : 'money', price : 1, description : '', name : '1М'},
        {id : 16, color : 'action', action : 'money', price : 1, description : '', name : '1М'},
        {id : 16, color : 'action', action : 'money', price : 1, description : '', name : '1М'},
        {id : 16, color : 'action', action : 'money', price : 1, description : '', name : '1М'},
        {id : 17, color : 'action', action : 'unfair', price : 10, description : '', name : 'Нечестная сделка'},
        {id : 17, color : 'action', action : 'unfair', price : 10, description : '', name : 'Нечестная сделка'},
        {id : 17, color : 'action', action : 'unfair', price : 10, description : '', name : 'Нечестная сделка'},
        {id : 17, color : 'action', action : 'unfair', price : 10, description : '', name : 'Нечестная сделка'},
        {id : 19, color : 'action', action : 'steal', price : 10, description : '', name : 'Сорви сделку'},
        {id : 19, color : 'action', action : 'steal', price : 10, description : '', name : 'Сорви сделку'},
        {id : 19, color : 'action', action : 'justno', price : 10, description : '', name : 'Скажи Нет'},
        {id : 19, color : 'action', action : 'justno', price : 10, description : '', name : 'Скажи Нет'},
        {id : 19, color : 'action', action : 'justno', price : 10, description : '', name : 'Скажи Нет'},
        {id : 14, color : 'action', action : 'tax', price : 10, description : '', name : 'Сборщик долгов'},
        {id : 14, color : 'action', action : 'tax', price : 10, description : '', name : 'Сборщик долгов'},
        {id : 14, color : 'action', action : 'tax', price : 10, description : '', name : 'Сборщик долгов'},
        {id : 15, color : 'action', action : 'birthday', price : 10, description : '', name : 'День рождения!'},
        {id : 15, color : 'action', action : 'birthday', price : 10, description : '', name : 'День рождения!'},
        {id : 15, color : 'action', action : 'birthday', price : 10, description : '', name : 'День рождения!'},
        {id : 14, color : 'action', action : 'start', price : 10, description : '', name : 'Пройди через старт'},
        {id : 14, color : 'action', action : 'start', price : 10, description : '', name : 'Пройди через старт'},
        {id : 14, color : 'action', action : 'start', price : 10, description : '', name : 'Пройди через старт'},
        {id : 14, color : 'action', action : 'start', price : 10, description : '', name : 'Пройди через старт'},
        {id : 14, color : 'action', action : 'start', price : 10, description : '', name : 'Пройди через старт'},
        {id : 14, color : 'action', action : 'start', price : 10, description : '', name : 'Пройди через старт'},
        {id : 14, color : 'action', action : 'start', price : 10, description : '', name : 'Пройди через старт'},
        {id : 14, color : 'action', action : 'start', price : 10, description : '', name : 'Пройди через старт'},
        {id : 14, color : 'action', action : 'start', price : 10, description : '', name : 'Пройди через старт'},
        {id : 14, color : 'action', action : 'start', price : 10, description : '', name : 'Пройди через старт'}
    ]
}